### ISSUE TITLE
 Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by georgel-pop** [terence55/themes-switch#2]
> breclient@0.0.0 dev-server C:\Users\extppg\Documents\Projects\audanet-fe\breclient
> cross-env region=core NODE_ENV=dev ./node_modules/.bin/webpack-dev-server --config webpack.config.js

Themes generating started...
(node:27396) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8181
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! breclient@0.0.0 dev-server: `cross-env region=core NODE_ENV=dev ./node_modules/.bin/webpack-dev-server --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the breclient@0.0.0 dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by terence55** [comment]
`ThemesGeneratorPlugin` already uses `.hooks` in webpack 4.x, the warning `Tapable.plugin is deprecated` may be caused by other plugins.

```
if (webpackNewVer) {
  compiler.hooks.entryOption.tap(pluginInfo, onEntryOption);
  compiler.hooks.emit.tapAsync(pluginInfo, onEmit);
  ...
}
```

Another tips, If you use webpack 4.x, `extract-text-webpack-plugin` and `html-webpack-plugin` should be updated to the lastest beta version.

```
"extract-text-webpack-plugin": "^4.0.0-beta.0",
 "html-webpack-plugin": "^4.0.0-beta.2",
```

If you need further help, please provide a reproducible demo in codesandbox or codepen.
