### ISSUE TITLE
Error: Rule can only have one resource source (provided resource and test + include + exclude)

### ISSUE THREAD

**Issue by ltoussaint** [terence55/themes-switch#3]
When a rule already use `resource`, we cannot add an `exclude` property but we need to add `resource.exclude`

I'll try a change and send a PR

**Comment by terence55** [comment]
`resource` is just a wrapper of test/include/exclude, you can also write `exclude` in a rule directly without `resource`.
But anyway it's a compatibility problem, I have fixed it in version 1.0.6, you can try it again.
