### ISSUE TITLE
ClearTemp after dev server ends?

### ISSUE THREAD

**Issue by WayneHiller** [terence55/themes-switch#8]
ThemesGeneratorPlugin.clearTemp
It will delete temp directory. You can call the method as needed, e.g. when you stop webpack-dev-server in development mode.

Do you have an example of how to do this?

**Comment by terence55** [comment]
For instance, if you are using create-react-app, you can edit the script `scripts/start.js`, and call `ThemesGeneratorPlugin.clearTemp` in the server shutdown function.
```
['SIGINT', 'SIGTERM'].forEach((sig) => {
      process.on(sig, () => {
        ThemesGeneratorPlugin.clearTemp();
        devServer.close();
        process.exit();
      });
    });
```
